import chalk from "chalk";
console.log(chalk.blue("1.Quesion1 of day2 100days of coding."));
console.log('Mark Twain once said," Good decisions come from experience and experience comes from making bad decisions."');
console.log(chalk.blue("2.Quesion2 of day2 100days of coding."));
let famousPerson = "Mark Twain";
let message = `${"famousPerson"} once said "Good decisions come from experience and experience comes from making bad decisions".`;
console.log(message);
console.log(chalk.blue("3.Quesion3 of day2 100days of coding."));
let whitespaceName = "\t\n Ghaniya khan \t\n";
console.log(chalk.blue(whitespaceName));
let withoutWhitespaceName = whitespaceName.trim();
console.log(chalk.blue(withoutWhitespaceName));
