import chalk from "chalk";
console.log(chalk.italic.bgGreen("Q1 and Q2"));
let num1 = 4;
let num2 = 4;
console.log(num1+num2);
let num3 = 10;
let num4 = 2;
console.log(num3-num4);
let num5 = 4;
let num6 = 2;
console.log(num6*num5);
let num7 = 2;
let num8 = 16;
console.log(num8/num7);
console.log(chalk.italic.bgGreen("2nd method"));
console.log(5+3);
console.log(15-7);
console.log(2*4);
console.log(32/4);
console.log(chalk.italic.bgGreen("Q3"))
let favNumber = 2 ;
console.log(chalk.yellow(`${favNumber} is my favourite number:)`));